name: iti_project
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  cloud_firestore: ^6.0.0
  convex_bottom_bar: ^3.2.0
  dartz: ^0.10.1
  dio: ^5.9.0
  equatable: ^2.0.7
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  firebase_storage: ^13.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0
  go_router: ^16.1.0
  google_sign_in: ^7.1.1
  hydrated_bloc: ^10.1.1
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
